/**
 * Static calendar rules — mirror of kpold-rules-top30-v2.json
 * Χρησιμοποιείται ως fallback όταν ο backend δεν έχει εκκινήσει.
 * Source: docs/research/kpold-rules-top30-v2.json (33 rules)
 *
 * Αυτό το αρχείο δεν πρέπει να γίνει import σε Server Components
 * που καλούν το API — μόνο σε client-side fallback.
 */

// Minimal type subset — full types στο types/calendar.ts
interface StaticRule {
  rule_id: string;
  kpold_article: string;
  title_gr: string;
  description_gr: string;
  trigger_event: string;
  duration: Record<string, unknown> | null;
  duration_foreign?: Record<string, unknown>;
  duration_katachristiki?: Record<string, unknown>;
  deadline_kind: string;
  business_days_only: boolean;
  skip_august: boolean;
  weekend_rollover: string;
  notes_gr: string;
  edge_cases: string[];
  frequency_score: number;
  last_amended_by: string;
  category?: string;
  // v2 fields
  version?: string;
  effective_from?: string;
  effective_until?: string | null;
  legal_source?: string;
  requires_legal_review?: boolean;
  warnings_gr?: string[];
}

const STATIC_RULES: StaticRule[] = [
  {
    rule_id: 'kpold-215-epidosi-agogis',
    kpold_article: '215 §2',
    title_gr: 'Επίδοση αγωγής μετά κατάθεση',
    description_gr: 'Μετά την κατάθεση της αγωγής, αντίγραφό της πρέπει να επιδοθεί στον εναγόμενο εντός 30 ημερών. Αν ο εναγόμενος ή ομόδικός του διαμένει στο εξωτερικό ή είναι άγνωστης διαμονής, η προθεσμία είναι 60 ημέρες.',
    trigger_event: 'κατάθεση_αγωγής',
    duration: { value: 30, unit: 'days' },
    duration_foreign: { value: 60, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Η μη τήρηση συνεπάγεται θεώρηση της αγωγής ως μη ασκηθείσας. Ισχύει στην τακτική διαδικασία από ν. 4335/2015.',
    edge_cases: ['Εναγόμενος στο εξωτερικό ή άγνωστης διαμονής: 60 ημέρες'],
    frequency_score: 10,
    last_amended_by: 'Ν. 4335/2015',
  },
  {
    rule_id: 'kpold-237-protaseis-taktiki',
    kpold_article: '237 §1',
    title_gr: 'Κατάθεση προτάσεων τακτικής διαδικασίας',
    description_gr: 'Στην τακτική διαδικασία, οι προτάσεις κατατίθενται εντός 90 ημερών από τη λήξη της προθεσμίας επίδοσης της αγωγής. Ισχύει για αμφότερους τους διαδίκους από ν. 4842/2021.',
    trigger_event: 'λήξη_προθεσμίας_επίδοσης_αγωγής_215§2',
    duration: { value: 90, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Ο Αύγουστος (1/8-31/8) δεν υπολογίζεται στην προθεσμία κατά ΚΠολΔ 144.',
    edge_cases: ['Αύγουστος εξαιρείται (ΚΠολΔ 144§1 εδ. β\')'],
    frequency_score: 10,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-237-prosthiki-antikrousi',
    kpold_article: '237 §2',
    title_gr: 'Προσθήκη - Αντίκρουση προτάσεων τακτικής',
    description_gr: 'Εντός 15 ημερών από τη λήξη της 90ήμερης προθεσμίας κατάθεσης προτάσεων, οι διάδικοι μπορούν να καταθέσουν προσθήκη-αντίκρουση.',
    trigger_event: 'λήξη_προθεσμίας_προτάσεων_237§1',
    duration: { value: 15, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Μετά τη λήξη της 15ήμερης, ο φάκελος κλείνει οριστικά.',
    edge_cases: ['Αύγουστος εξαιρείται'],
    frequency_score: 10,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-518-efesi-gnisia',
    kpold_article: '518 §1',
    title_gr: 'Έφεση — γνήσια προθεσμία (από επίδοση)',
    description_gr: 'Η προθεσμία άσκησης έφεσης είναι 30 ημέρες από την επίδοση της εκκαλούμενης απόφασης (εντός Ελλάδος). Αν διαμένει στο εξωτερικό: 60 ημέρες.',
    trigger_event: 'επίδοση_απόφασης_πρωτοβάθμιου',
    duration: { value: 30, unit: 'days' },
    duration_foreign: { value: 60, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Γνήσια προθεσμία: τρέχει μόνο αν η απόφαση επιδόθηκε. Αύγουστος εξαιρείται.',
    edge_cases: ['Διαμονή εξωτερικού: 60 ημέρες', 'Αύγουστος δεν υπολογίζεται'],
    frequency_score: 10,
    last_amended_by: 'Ν. 4335/2015 + Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-518-efesi-katachristiki',
    kpold_article: '518 §2',
    title_gr: 'Έφεση — καταχρηστική προθεσμία (χωρίς επίδοση) — ΔΥΑΔΙΚΗ ΕΚΔΟΧΗ',
    description_gr: 'Αν η απόφαση δεν επιδόθηκε ποτέ: (α) αποφάσεις ΕΩΣ 31/12/2025: 2 έτη από δημοσίευση. (β) αποφάσεις ΑΠΟ 1/1/2026: 1 έτος από δημοσίευση (Ν. 5221/2025 άρθρο 44).',
    trigger_event: 'δημοσίευση_απόφασης_πρωτοβάθμιου',
    duration: null,
    deadline_kind: 'αποκλειστική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΔΥΑΔΙΚΗ ΕΚΔΟΧΗ: Απαιτείται ημερομηνία δημοσίευσης. Αναστολή Αυγούστου: ΝΑΙ (ΑΠ 1357/2025).',
    edge_cases: [
      'Αποφάσεις 2016-2025: 2 έτη (μεταβατική Ν. 5264/2025 άρθρο 114§4)',
      'Αποφάσεις 2026+: 1 έτος (Ν. 5221/2025 άρθρο 44)',
    ],
    frequency_score: 7,
    last_amended_by: 'Ν. 5221/2025 άρθρο 44 + μεταβατική Ν. 5264/2025 άρθρο 114§4',
    version: 'v2',
    effective_from: '2026-01-01',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 άρθρο 44 + μεταβατική Ν. 5264/2025 άρθρο 114§4',
    requires_legal_review: false,
    warnings_gr: [
      'ΚΡΙΣΙΜΟ: Η καταχρηστική έφεσης εξαρτάται από ημερομηνία δημοσίευσης. Αποφάσεις ΕΩΣ 31/12/2025: 2 έτη. ΑΠΟ 1/1/2026: 1 έτος. Αναστολή Αυγούστου: ΝΑΙ (ΑΠ 1357/2025).',
    ],
  },
  {
    rule_id: 'kpold-503-anakopi-erimodikias',
    kpold_article: '503 §1',
    title_gr: 'Ανακοπή ερημοδικίας',
    description_gr: 'Ο διάδικος που δικάστηκε ερήμην δικαιούται να ασκήσει ανακοπή ερημοδικίας. 15 ημέρες από επίδοση ερήμην απόφασης (Ελλάδα) ή 30 ημέρες (εξωτερικό).',
    trigger_event: 'επίδοση_ερήμην_απόφασης',
    duration: { value: 15, unit: 'days' },
    duration_foreign: { value: 30, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Δεν προβλέπεται καταχρηστική προθεσμία.',
    edge_cases: ['Αν δεν έγινε επίδοση: η ανακοπή ασκείται ανά πάσα στιγμή'],
    frequency_score: 9,
    last_amended_by: 'ΚΠολΔ αρχικό + Ν. 4335/2015',
  },
  {
    rule_id: 'kpold-545-anapsilafisi',
    kpold_article: '544-545',
    title_gr: 'Αναψηλάφηση — προθεσμία άσκησης',
    description_gr: 'Η αναψηλάφηση ασκείται εντός 60 ημερών (Ελλάδα) ή 120 ημερών (εξωτερικό). Καταχρηστική: 3 έτη από δημοσίευση.',
    trigger_event: 'ανακάλυψη_λόγου_αναψηλάφησης_ή_επίδοση_απόφασης',
    duration: { value: 60, unit: 'days' },
    duration_foreign: { value: 120, unit: 'days' },
    duration_katachristiki: { value: 3, unit: 'years' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Λόγοι αναψηλάφησης: ΚΠολΔ 544 (περιοριστικός κατάλογος).',
    edge_cases: ['Αφετηρία ποικίλει ανά λόγο ΚΠολΔ 544'],
    frequency_score: 5,
    last_amended_by: 'ΚΠολΔ αρχικό',
  },
  {
    rule_id: 'kpold-564-anairesi-gnisia',
    kpold_article: '564 §1',
    title_gr: 'Αναίρεση — γνήσια προθεσμία',
    description_gr: 'Η αναίρεση ασκείται εντός 30 ημερών από την επίδοση της τελεσίδικης απόφασης (Ελλάδα) ή 60 ημερών (εξωτερικό).',
    trigger_event: 'επίδοση_τελεσίδικης_απόφασης',
    duration: { value: 30, unit: 'days' },
    duration_foreign: { value: 60, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Αφορά μόνο τελεσίδικες αποφάσεις. Αύγουστος εξαιρείται.',
    edge_cases: ['Διαμονή εξωτερικού: 60 ημέρες'],
    frequency_score: 8,
    last_amended_by: 'Ν. 4335/2015 + Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-564-anairesi-katachristiki',
    kpold_article: '564 §3',
    title_gr: 'Αναίρεση — καταχρηστική προθεσμία — ΔΥΑΔΙΚΗ ΕΚΔΟΧΗ',
    description_gr: 'Αν η τελεσίδικη απόφαση δεν επιδόθηκε: (α) δημοσίευση ΕΩΣ 31/12/2025: 2 έτη. (β) δημοσίευση ΑΠΟ 1/1/2026: 1 έτος (Ν. 5221/2025 άρθρο 53).',
    trigger_event: 'δημοσίευση_τελεσίδικης_απόφασης',
    duration: null,
    deadline_kind: 'αποκλειστική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΔΥΑΔΙΚΗ ΕΚΔΟΧΗ. Αναστολή Αυγούστου: ΝΑΙ (ΑΠ 2056/2025).',
    edge_cases: [
      'Αποφάσεις 2016-2025: 2 έτη (μεταβατική Ν. 5264/2025 άρθρο 114§4)',
      'Αποφάσεις 2026+: 1 έτος (Ν. 5221/2025 άρθρο 53)',
    ],
    frequency_score: 5,
    last_amended_by: 'Ν. 5221/2025 άρθρο 53 + μεταβατική Ν. 5264/2025 άρθρο 114§4',
    version: 'v2',
    effective_from: '2026-01-01',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 άρθρο 53 + μεταβατική Ν. 5264/2025 άρθρο 114§4',
    requires_legal_review: false,
    warnings_gr: [
      'ΚΡΙΣΙΜΟ: Καταχρηστική αναίρεσης (ΚΠολΔ 564§3): ΕΩΣ 31/12/2025 = 2 έτη, ΑΠΟ 1/1/2026 = 1 έτος. Αναστολή Αυγούστου: ΝΑΙ (ΑΠ 2056/2025).',
    ],
  },
  {
    rule_id: 'kpold-583-tritanakopi',
    kpold_article: '583-586',
    title_gr: 'Τριτανακοπή — προθεσμία άσκησης',
    description_gr: 'Τρίτος που θίγεται από δικαστική απόφαση: 60 ημέρες από κοινοποίηση ή γνώση. Καταχρηστική: 3 έτη από δημοσίευση.',
    trigger_event: 'κοινοποίηση_ή_γνώση_απόφασης',
    duration: { value: 60, unit: 'days' },
    duration_katachristiki: { value: 3, unit: 'years' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Αύγουστος εξαιρείται από 60ήμερη.',
    edge_cases: ['Καταχρηστική: 3 έτη από δημοσίευση'],
    frequency_score: 4,
    last_amended_by: 'ΚΠολΔ αρχικό',
  },
  {
    rule_id: 'kpold-632-anakopi-diatagis-pliromis',
    kpold_article: '632 §1',
    title_gr: 'Ανακοπή κατά διαταγής πληρωμής',
    description_gr: '15 εργάσιμες ημέρες από επίδοση διαταγής πληρωμής (Ελλάδα) ή 30 εργάσιμες (εξωτερικό). Από 16/9/2026: νέο ΚΠολΔ 633 επιτρέπει ανακοπή και πριν 2η επίδοση.',
    trigger_event: 'επίδοση_διαταγής_πληρωμής',
    duration: { value: 15, unit: 'business_days' },
    duration_foreign: { value: 30, unit: 'business_days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: true,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΕΡΓΑΣΙΜΕΣ ημέρες. Η ανακοπή δεν αναστέλλει αυτομάτως την εκτέλεση. ΚΡΙΣΙΜΟ: Εκκρεμείς ανακοπές 632 με δικάσιμο μετά 16/9/2026 — βλ. kpold-130-epanaprosdiorismos-ekkremon.',
    edge_cases: ['Εργάσιμες ημέρες — ΟΧΙ ημερολογιακές', 'Αύγουστος εξαιρείται', 'Εκκρεμείς ανακοπές με δικάσιμο > 16/9/2026: απαιτείται αίτηση επαναπροσδιορισμού'],
    frequency_score: 10,
    last_amended_by: 'Ν. 4335/2015 + Ν. 4842/2021 + Ν. 5221/2025 (νέο 633) + Ν. 5264/2025 άρθρο 142',
    version: 'v2',
    effective_from: '2026-09-16',
    effective_until: null,
    legal_source: 'ΚΠολΔ 632§1 + νέο 633 (Ν. 5221/2025 + Ν. 5264/2025 άρθρο 142)',
    requires_legal_review: true,
  },
  {
    rule_id: 'kpold-630a-epidosi-diatagis-pliromis',
    kpold_article: '630Α',
    title_gr: 'Επίδοση διαταγής πληρωμής (2μηνη προθεσμία)',
    description_gr: 'Η διαταγή πληρωμής πρέπει να επιδοθεί εντός 2 μηνών από την έκδοσή της. Αν παρέλθει: ακυρώνεται αυτοδικαίως. Από 16/9/2026: αφετηρία = έκδοση ΔΠ από δικηγόρο (νέο ΚΠολΔ 625 + Ν. 5264/2025 άρθρο 142).',
    trigger_event: 'έκδοση_ΔΠ_από_δικηγόρο_ή_δικαστή',
    duration: { value: 2, unit: 'months' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Η προθεσμία του 630Α ΔΕΝ αναστέλλεται τον Αύγουστο (ΑΠ 948/2007, ΑΠ 1538/2007). Από 16/9/2026: αφετηρία = έκδοση ΔΠ από δικηγόρο. ΕΩΣ 15/9/2026: παλαιό σύστημα (δικαστής).',
    edge_cases: [
      'Αύγουστος ΔΕΝ αναστέλλει αυτήν την προθεσμία (ΑΠ 948/2007, ΑΠ 1538/2007)',
      'Από 16/9/2026: αφετηρία = έκδοση ΔΠ από δικηγόρο (νέο ΚΠολΔ 625 + Ν. 5264/2025 άρθρο 142)',
      'ΕΩΣ 15/9/2026: παλαιό σύστημα (δικαστής)',
    ],
    frequency_score: 9,
    last_amended_by: 'Ν. 4335/2015 + Ν. 5221/2025 (νέο 625) + Ν. 5264/2025 άρθρο 142',
    version: 'v2',
    effective_from: '2026-09-16',
    effective_until: null,
    legal_source: 'ΚΠολΔ 630Α (Ν. 4335/2015) + Ν. 5221/2025 άρθρα 68 επ. (νέο 625) + Ν. 5264/2025 άρθρο 142',
    requires_legal_review: false,
    warnings_gr: [
      'ΠΡΟΣΟΧΗ: Η δίμηνη (ΚΠολΔ 630Α) ΔΕΝ αναστέλλεται τον Αύγουστο. Από 16/9/2026: αφετηρία = έκδοση ΔΠ από δικηγόρο (Ν. 5264/2025 άρθρο 142). ΕΩΣ 15/9/2026: παλαιό σύστημα (δικαστής).',
    ],
  },
  {
    rule_id: 'kpold-933-anakopi-ektelesis',
    kpold_article: '933-934',
    title_gr: 'Ανακοπή κατά αναγκαστικής εκτέλεσης',
    description_gr: '45 ημέρες από κατάσχεση (λόγοι 1ου σταδίου). Λόγοι 2ου σταδίου: 15 εργάσιμες πριν τον πλειστηριασμό.',
    trigger_event: 'ημέρα_κατάσχεσης',
    duration: { value: 45, unit: 'days' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Διπλή προθεσμία: 45 ημέρες από κατάσχεση + 15 εργάσιμες πριν πλειστηριασμό.',
    edge_cases: ['Αύγουστος εξαιρείται από 45ήμερη'],
    frequency_score: 9,
    last_amended_by: 'Ν. 4335/2015 + Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-954-pleistariasmou-oria',
    kpold_article: '954 §2',
    title_gr: 'Πλειστηριασμός — χρόνος διενέργειας μετά κατάσχεση',
    description_gr: 'Ο πλειστηριασμός ορίζεται από τον 7ο έως τον 8ο μήνα μετά την κατάσχεση. Αν λήξη σε Αύγουστο: μεταφέρεται στον Σεπτέμβριο.',
    trigger_event: 'περάτωση_κατάσχεσης',
    duration: { value_min: 7, value_max: 8, unit: 'months' },
    deadline_kind: 'ενδεικτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Ο Αύγουστος προσμετράται αλλά αν η λήξη εμπίπτει σε Αύγουστο — μεταφέρεται.',
    edge_cases: ['Λήξη σε Αύγουστο: μεταφέρεται στον Σεπτέμβριο'],
    frequency_score: 7,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-693-asfalistika-kyria-agogi',
    kpold_article: '693 §1',
    title_gr: 'Ασφαλιστικά μέτρα — προθεσμία κύριας αγωγής',
    description_gr: 'Αν το ασφαλιστικό μέτρο διατάχθηκε πριν κύριας αγωγής, ο αιτών πρέπει να ασκήσει αγωγή εντός 30 ημερών από την ΕΚΔΟΣΗ της απόφασης ασφαλιστικών (ΑΠ 957/2021). Αύγουστος ΔΕΝ αναστέλλει.',
    trigger_event: 'έκδοση_απόφασης_ασφαλιστικών_μέτρων',
    duration: { value: 30, unit: 'days', note: 'ελάχιστη — ορίζεται από δικαστή' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'OVERRIDE v1: Αφετηρία = ΕΚΔΟΣΗ απόφασης (ΟΧΙ επίδοση) — ΑΠ 957/2021. Αύγουστος ΔΕΝ αναστέλλει.',
    edge_cases: [
      'Αφετηρία = ΕΚΔΟΣΗ απόφασης ασφαλιστικών (ΟΧΙ επίδοση) — ΑΠ 957/2021',
      'Αύγουστος ΔΕΝ αναστέλλει',
      'Αν ήδη εκκρεμεί κύρια αγωγή: δεν απαιτείται νέα άσκηση',
    ],
    frequency_score: 8,
    last_amended_by: 'Ν. 4842/2021 + ΑΠ 957/2021',
    version: 'v2',
    effective_from: '2021-01-01',
    effective_until: null,
    legal_source: 'ΚΠολΔ 693§1 (Ν. 4842/2021) + ΑΠ 957/2021',
    requires_legal_review: false,
    warnings_gr: [
      'Η 30ήμερη (ΚΠολΔ 693§1) εκκινεί από ΕΚΔΟΣΗ απόφασης ασφαλιστικών (ΟΧΙ επίδοση). Αύγουστος ΔΕΝ αναστέλλει.',
    ],
  },
  {
    rule_id: 'kpold-144-exairetees-imeres',
    kpold_article: '144',
    title_gr: 'Εξαιρετέες ημέρες — γενικός κανόνας υπολογισμού',
    description_gr: 'Γενικός κανόνας: δεν υπολογίζεται η ημέρα έναρξης. Αν τελευταία ημέρα = Κυριακή/αργία/Σάββατο → παρατείνεται. Αύγουστος εξαιρείται σύμφωνα με ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51), ΟΧΙ σε νέα §4 του 144.',
    trigger_event: 'οποιαδήποτε_έναρξη_προθεσμίας',
    duration: null,
    deadline_kind: 'γενικός_κανόνας',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΒΑΣΙΚΟΣ κανόνας που εφαρμόζεται σε ΟΛΑ τα rules. Η ρητή λίστα αναστολής Αυγούστου: ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51).',
    edge_cases: [
      'Σάββατο = εξαιρετέα ημέρα (από ν. 4335/2015)',
      'Ρητή λίστα αναστολής Αυγούστου: ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51) — ΟΧΙ νέα §4 του 144',
    ],
    frequency_score: 10,
    last_amended_by: 'Ν. 4335/2015 + ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51)',
    version: 'v2',
    effective_from: '2022-07-29',
    effective_until: null,
    legal_source: 'ΚΠολΔ 144 (Ν. 4335/2015) + ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51)',
    requires_legal_review: true,
  },
  {
    rule_id: 'kpold-144-par2-exoteriko',
    kpold_article: '144 §2',
    title_gr: 'Παρέκταση προθεσμίας για κατοίκους εξωτερικού',
    description_gr: 'Για διαδίκους εξωτερικού ή άγνωστης διαμονής: +30 ημέρες επί τακτικών προθεσμιών (εκτός ρητής ειδικής ρύθμισης).',
    trigger_event: 'οποιαδήποτε_έναρξη_προθεσμίας_για_εξωτερικό',
    duration: { value: 30, unit: 'days', note: 'πρόσθετη παρέκταση' },
    deadline_kind: 'γενικός_κανόνας',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Γενική παρέκταση +30 ημέρες.',
    edge_cases: ['Άγνωστη διαμονή εξισώνεται με εξωτερικό'],
    frequency_score: 7,
    last_amended_by: 'ΚΠολΔ αρχικό',
  },
  {
    rule_id: 'kpold-591-ergatikes-protaseis',
    kpold_article: '591 §1 (ειδική διαδ.)',
    title_gr: 'Εργατικές/Μισθωτικές — αντίκρουση πριν δικάσιμο',
    description_gr: 'Στις ειδικές διαδικασίες, αντίκρουση/προσθήκη κατατίθεται τουλάχιστον 8 ημέρες πριν τη συζήτηση.',
    trigger_event: 'ορισμός_δικασίμου_ειδικής_διαδικασίας',
    duration: { value: 8, unit: 'days', note: 'πριν από ημέρα συζήτησης' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Κύριες προτάσεις: κατατίθενται αυθημερόν στο ακροατήριο.',
    edge_cases: ['Αντίκρουση: υποχρεωτικά 8 ημέρες πριν + επίδοση'],
    frequency_score: 8,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-215-agogi-epidosi-klisi',
    kpold_article: '215 §1 + 226',
    title_gr: 'Κλήση για συζήτηση — προθεσμία επίδοσης',
    description_gr: 'Κλήση για δικάσιμο επιδίδεται τουλάχιστον 30 ημέρες πριν (ημεδαποί) ή 60 ημέρες (αλλοδαποί).',
    trigger_event: 'ορισμός_δικασίμου_και_σύνταξη_κλήσης',
    duration: { value: 30, unit: 'days', note: 'πριν δικάσιμο' },
    duration_foreign: { value: 60, unit: 'days', note: 'πριν δικάσιμο' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Αφορά κλήση για συζήτηση — διαφορετική από κλήτευση αγωγής.',
    edge_cases: ['Κατοικία εξωτερικού: 60 ημέρες πριν'],
    frequency_score: 8,
    last_amended_by: 'ΚΠολΔ αρχικό + Ν. 4335/2015',
  },
  {
    rule_id: 'kpold-260-mataiosi-orismou',
    kpold_article: '260',
    title_gr: 'Ματαίωση συζήτησης — εκ νέου κλήση',
    description_gr: 'Μετά ματαίωση, νέα κλήση επιδίδεται 30 ημέρες πριν (ημεδαποί) ή 60 ημέρες (αλλοδαποί).',
    trigger_event: 'ματαίωση_συζήτησης',
    duration: { value: 30, unit: 'days', note: 'πριν νέα δικάσιμο' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Αυτεπάγγελτος προσδιορισμός νέας δικασίμου από ν. 4842/2021.',
    edge_cases: ['Αν δεν επισπευσθεί εντός 6 μηνών: κατάργηση δίκης κατ\' άρθρο 286'],
    frequency_score: 7,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-938-anastoli-ektelesis',
    kpold_article: '938',
    title_gr: 'Αίτηση αναστολής εκτέλεσης κατά εκκρεμούσας ανακοπής',
    description_gr: 'Εφόσον εκκρεμεί ανακοπή, ο ανακόπτων μπορεί να ζητήσει αναστολή. Πρέπει να υποβληθεί εντόκως ώστε να εκδικαστεί πριν τον πλειστηριασμό.',
    trigger_event: 'άσκηση_ανακοπής_933',
    duration: null,
    deadline_kind: 'ενδεικτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Ασκείται πρακτικά ταυτόχρονα ή αμέσως μετά ανακοπή.',
    edge_cases: ['Αν πλειστηριασμός διεξαχθεί πριν εκδικαστεί: άνευ αντικειμένου'],
    frequency_score: 8,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-286-katargi-dikis',
    kpold_article: '286',
    title_gr: 'Κατάργηση δίκης λόγω αδράνειας',
    description_gr: 'Αν δεν οριστεί νέα δικάσιμος εντός 6 μηνών από αναβολή/ματαίωση, η δίκη καταργείται.',
    trigger_event: 'ματαίωση_ή_αναβολή_συζήτησης',
    duration: { value: 6, unit: 'months' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Η κατάργηση δεν κωλύει νέα αγωγή — παραγραφή όμως τρέχει.',
    edge_cases: ['Η κατάργηση δεν αίρει την παραγραφή'],
    frequency_score: 6,
    last_amended_by: 'ΚΠολΔ αρχικό + Ν. 4335/2015',
  },
  {
    rule_id: 'kpold-misthiotikes-agogi',
    kpold_article: '647-661',
    title_gr: 'Μισθωτικές διαφορές — αγωγή και δικάσιμος',
    description_gr: 'Μισθωτικές διαφορές: ειδική διαδικασία. Δικάσιμος τουλάχιστον 30 ημέρες μετά επίδοση.',
    trigger_event: 'κατάθεση_αγωγής_μισθωτικής',
    duration: { value: 30, unit: 'days', note: 'μεταξύ επίδοσης και δικασίμου' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Ειδική διαδικασία — πολύ ταχύτερη από τακτική.',
    edge_cases: ['Αντίκρουση: 8 ημέρες πριν τη δικάσιμο'],
    frequency_score: 8,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-ergatikes-agogi',
    kpold_article: '663-676',
    title_gr: 'Εργατικές διαφορές — αγωγή και δικάσιμος',
    description_gr: 'Εργατικές διαφορές: ειδική διαδικασία. Δικάσιμος τουλάχιστον 60 ημέρες μετά επίδοση (ημεδαποί).',
    trigger_event: 'κατάθεση_αγωγής_εργατικής',
    duration: { value: 60, unit: 'days', note: 'μεταξύ επίδοσης και δικασίμου' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Εργατικές: ειδική διαδικασία — ταχύτερη από τακτική.',
    edge_cases: ['Αντίκρουση/προσθήκη: 8 ημέρες πριν δικάσιμο'],
    frequency_score: 8,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-oikogeniakes-diafores',
    kpold_article: '592-613',
    title_gr: 'Οικογενειακές διαφορές — ειδική διαδικασία',
    description_gr: 'Οικογενειακές διαφορές: κλήτευση αντίδικου 60 ημέρες πριν δικάσιμο (ημεδαποί) ή 90 ημέρες (αλλοδαποί).',
    trigger_event: 'κατάθεση_αγωγής_οικογενειακής',
    duration: { value: 60, unit: 'days', note: 'μεταξύ επίδοσης και δικασίμου' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Αυτεπάγγελτη εξέταση ορισμένων ζητημάτων (πχ συμφέρον τέκνου).',
    edge_cases: ['Αλλοδαποί διάδικοι: 90 ημέρες πριν'],
    frequency_score: 7,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-ekousia-anakopi',
    kpold_article: '739-866',
    title_gr: 'Εκούσια δικαιοδοσία — κλήτευση ενδιαφερομένων',
    description_gr: 'Εκούσια δικαιοδοσία: κλήτευση ενδιαφερομένων 30 ημέρες πριν δικάσιμο.',
    trigger_event: 'κατάθεση_αίτησης_εκούσιας',
    duration: { value: 30, unit: 'days', note: 'μεταξύ επίδοσης και δικασίμου' },
    deadline_kind: 'ενδεικτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Δικαστής: ευρύτερη διακριτική ευχέρεια.',
    edge_cases: ['Κλήτευση εισαγγελέα: ορισμένες κατηγορίες'],
    frequency_score: 5,
    last_amended_by: 'Ν. 4335/2015',
  },
  {
    rule_id: 'kpold-ak-paragrafos-penta',
    kpold_article: 'ΑΚ 250',
    title_gr: 'Πενταετής παραγραφή — συμβατικές αξιώσεις',
    description_gr: 'Η γενική παραγραφή αξιώσεων από συμβάσεις (αμοιβή, δάνειο, αδικοπραξία) είναι 5 έτη από τη γένεση.',
    trigger_event: 'γένεση_αξίωσης_ή_γνώση_ζημίας',
    duration: { value: 5, unit: 'years' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Διαφορά παραγραφής ΑΚ (ουσιαστικό δίκαιο) από δικονομικές προθεσμίες ΚΠολΔ.',
    edge_cases: ['ΑΚ 862: 3ετής δικηγόρου'],
    frequency_score: 9,
    last_amended_by: 'ΑΚ αρχικό',
  },
  {
    rule_id: 'kpold-ak-paragrafos-dikigoros',
    kpold_article: 'Ν. 4194/2013 άρθρο 58 (Κώδικας Δικηγόρων)',
    title_gr: 'Πενταετής παραγραφή αξιώσεων δικηγόρου',
    description_gr: 'Αξιώσεις δικηγόρου για αμοιβή: ΠΕΝΤΑΕΤΗΣ παραγραφή. Αφετηρία: τέλος ημ. έτους κατά το οποίο ενεργήθηκε (α) η σχετική πράξη (εξώδικα) ή (β) η τελευταία διαδικαστική πράξη ΑΠΟ ΤΟΝ ΔΙΚΗΓΟΡΟ (δίκες).',
    trigger_event: 'τέλος_ημερολογιακού_έτους_τελευταίας_πράξης_δικηγόρου',
    duration: { value: 5, unit: 'years' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΔΙΟΡΘΩΣΗ v1: 5 έτη (ΟΧΙ 3). Νομική βάση: Ν. 4194/2013 άρθρο 58 (ΟΧΙ ΑΚ 862). Τελ. πράξη 15/06/2023 → αφετηρία 31/12/2023 → λήξη 31/12/2028.',
    edge_cases: [
      'Τελευταία πράξη δικηγόρου 15/06/2023 → αφετηρία 31/12/2023 → λήξη 31/12/2028',
      'ΑΚ 862 = εντελώς διαφορετική διάταξη (ψυχική ζημία) — σύγχυση στο v1',
      'Αναγνώριση χρέους εγγράφως = διακοπή (ΑΚ 260)',
    ],
    frequency_score: 8,
    last_amended_by: 'Ν. 4194/2013 άρθρο 58',
    version: 'v2',
    effective_from: '2014-01-01',
    effective_until: null,
    legal_source: 'Ν. 4194/2013 άρθρο 58 + ΑΠ 853/2010, ΑΠ 1276/2018, ΑΠ 949/2020',
    requires_legal_review: false,
    warnings_gr: [
      'Η παραγραφή αξιώσεων δικηγόρου είναι ΠΕΝΤΑΕΤΗΣ (Ν. 4194/2013 άρθρο 58), ΟΧΙ τριετής. Αφετηρία = τέλος ημ. έτους κατά το οποίο ενεργήθηκε η τελευταία πράξη ΑΠΟ ΤΟΝ ΔΙΚΗΓΟΡΟ (ΑΠ 853/2010, ΑΠ 1276/2018).',
    ],
  },
  {
    rule_id: 'kpold-954-anakopi-pleistariasmou',
    kpold_article: '954 §4 εδ. α\'',
    title_gr: 'Ανακοπή κατά πλειστηριασμού — 15 εργάσιμες πριν',
    description_gr: 'Ανακοπή κατά πράξεων μετά κατάθεση εγγράφων στον συμβολαιογράφο: 15 εργάσιμες ημέρες πριν τον πλειστηριασμό.',
    trigger_event: 'αυτεπάγγελτη_κατάθεση_εγγράφων_συμβολαιογράφου',
    duration: { value: 15, unit: 'business_days_before_auction' },
    deadline_kind: 'ανατρεπτική',
    business_days_only: true,
    skip_august: true,
    weekend_rollover: 'previous_business_day',
    notes_gr: 'Αντίστροφη αρίθμηση: 15 εργάσιμες ΠΡΟ πλειστηριασμού.',
    edge_cases: ['Αν πλειστηριασμός ακυρωθεί: νέα προθεσμία τρέχει'],
    frequency_score: 7,
    last_amended_by: 'Ν. 4842/2021',
  },
  {
    rule_id: 'kpold-diakopes-augoustos',
    kpold_article: '11 Ν. 1756/1988 + ΚΠολΔ 147§2',
    title_gr: 'Δικαστικές διακοπές Αυγούστου — αναστολή προθεσμιών',
    description_gr: 'Κατά Αύγουστο (1-31/8): αναστέλλονται σύμφωνα με ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51): προτάσεις (237), αντίκρουση (238), ένδικα μέσα (503, 518§1, 545§§1-2, 564§§1-2), 632§2, 633§2, 934§1α&β κ.ά. ΔΕΝ αναστέλλονται: 630Α (επίδοση ΔΠ), 693 (ασφαλιστικά).',
    trigger_event: '1η_Αυγούστου',
    duration: { value: 31, unit: 'days' },
    deadline_kind: 'γενικός_κανόνας',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΠΡΑΚΤΙΚΟΣ ΚΑΝΟΝΑΣ: Αν προθεσμία τρέχει τον Αύγουστο → παγώνει, ξανατρέχει 1η Σεπτεμβρίου. Νομική βάση: ΚΠολΔ 147§2 (Ν. 4963/2022 άρθρο 51), ΟΧΙ νέα §4 του 144.',
    edge_cases: [
      'Έφεση (518§1): αναστέλλεται (ΚΠολΔ 147§2)',
      'Επίδοση ΔΠ (630Α): ΔΕΝ αναστέλλεται (ΑΠ 948/2007)',
      'Ανακοπή εκτέλεσης (934§1α&β): αναστέλλεται — ρητά στο 147§2',
      'NEEDS_LEGAL_REVIEW: καταχρηστικές 518§2/564§3 (νομολογιακή επιφύλαξη)',
    ],
    frequency_score: 10,
    last_amended_by: 'ΚΠολΔ 147§2 + Ν. 1756/1988 + Ν. 4963/2022 άρθρο 51',
    version: 'v2',
    effective_from: '2022-07-29',
    effective_until: null,
    legal_source: 'ΚΠολΔ 147§2 (ως ισχύει μετά Ν. 4963/2022 άρθρο 51, ΦΕΚ Α 149/29-7-2022) + Ν. 1756/1988 άρθρο 11',
    requires_legal_review: true,
  },
  {
    rule_id: 'kpold-epidosi-vs-koinopoiisi',
    kpold_article: '123-142',
    title_gr: 'Επίδοση vs. Κοινοποίηση — αφετηρία προθεσμιών',
    description_gr: 'Η επίδοση (δικαστικός επιμελητής) αποτελεί αφετηρία προθεσμιών ενδίκων μέσων. Η κοινοποίηση ΔΕΝ ισοδυναμεί με επίδοση.',
    trigger_event: 'πράξη_επίδοσης_δικαστικού_επιμελητή',
    duration: null,
    deadline_kind: 'γενικός_κανόνας',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΚΡΙΣΙΜΗ ΔΙΑΚΡΙΣΗ: Επίδοση = επίσημη πράξη δικαστικού επιμελητή.',
    edge_cases: ['Ηλεκτρονική επίδοση (e-εξεπικίσιο): ισοδύναμη από ν. 4335/2015'],
    frequency_score: 9,
    last_amended_by: 'Ν. 4335/2015',
  },
  // -------------------------------------------------------------------------
  // Νέοι κανόνες v2 (Ν. 5221/2025)
  // -------------------------------------------------------------------------
  {
    rule_id: 'kpold-625-dp-dikigoros-ekdosi',
    kpold_article: 'ΚΠολΔ 625 (νέο, Ν. 5221/2025)',
    title_gr: 'Διαταγή Πληρωμής — Νέο Σύστημα (από δικηγόρο) — ΑΠΟ 16/9/2026',
    description_gr: 'Από 16/9/2026 η ΔΠ εκδίδεται από δικηγόρο (4ετής πείρα + ειδική κατάρτιση) εγγεγραμμένο στον κατάλογο Ολομέλειας. ΔΠ πριν 16/9/2026: συνεχίζουν κατά παλαιό σύστημα (δικαστής). Ημερομηνία μετατέθηκε από 1/1/2026 (Ν. 5264/2025 άρθρο 142).',
    trigger_event: 'υποβολή_αίτησης_έκδοσης_ΔΠ',
    duration: null,
    deadline_kind: 'γενικός_κανόνας',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Νέο σύστημα από 16/9/2026 (ΟΧΙ 1/1/2026). Αφετηρία 630Α = έκδοση ΔΠ από δικηγόρο. BETA: feature_flag BETA_DISABLED_UNTIL_2026-09-16.',
    edge_cases: [
      'ΔΠ πριν 16/9/2026: παλαιό σύστημα (δικαστής) — νέο σύστημα ΔΕΝ εφαρμόζεται',
      'ΔΠ από 16/9/2026: νέο σύστημα (δικηγόρος με κατάρτιση)',
      'Ημερομηνία ισχύος μετατέθηκε από 1/1/2026 σε 16/9/2026 (Ν. 5264/2025 άρθρο 142)',
    ],
    frequency_score: 10,
    last_amended_by: 'Ν. 5221/2025 άρθρα 68 επ. + Ν. 5264/2025 άρθρο 142',
    version: 'v2',
    effective_from: '2026-09-16',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 άρθρα 68 επ. (νέο ΚΠολΔ 625) + Ν. 5264/2025 άρθρο 142 (μετάθεση ισχύος)',
    requires_legal_review: true,
    warnings_gr: [
      'BETA: Το νέο σύστημα ΔΠ από δικηγόρο ισχύει από 16/9/2026 (ΟΧΙ 1/1/2026). Πριν αυτή την ημερομηνία εφαρμόζεται παλαιό σύστημα (έκδοση από δικαστή). Ν. 5264/2025 άρθρο 142.',
    ],
  },
  {
    rule_id: 'kpold-933-ekdikasi-prothesmia',
    kpold_article: 'ΚΠολΔ 933 (τροπ. Ν. 5221/2025 άρθρα 104-105)',
    title_gr: 'Ανακοπή εκτέλεσης — υποχρεωτικές προθεσμίες εκδίκασης (από 1/1/2026)',
    description_gr: 'Από 1/1/2026: εκδίκαση εντός 60 ημερών από κατάθεση. Κλήτευση: 20 ημέρες πριν. Απόφαση: εντός 60 ημερών από συζήτηση. Αυτές είναι ΥΠΟΧΡΕΩΣΕΙΣ ΔΙΚΑΣΤΗΡΙΟΥ.',
    trigger_event: 'κατάθεση_ανακοπής_933',
    duration: { value: 60, unit: 'days' },
    deadline_kind: 'δικαστική_υποχρέωση',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'Προθεσμίες ΕΚΔΙΚΑΣΗΣ (υποχρέωση δικαστηρίου, reminder για δικηγόρο). 45ήμερη ΑΣΚΗΣΗΣ: NEEDS_LEGAL_REVIEW.',
    edge_cases: [
      'Κλήτευση: 20 ημέρες πριν συζήτηση',
      'Απόφαση: εντός 60 ημερών από συζήτηση',
      '45ήμερη ΑΣΚΗΣΗΣ από κατάσχεση: NEEDS_LEGAL_REVIEW',
    ],
    frequency_score: 8,
    last_amended_by: 'Ν. 5221/2025 άρθρα 104-105',
    version: 'v2',
    effective_from: '2026-01-01',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 άρθρα 104-105 (τροπ. ΚΠολΔ 933-934)',
    requires_legal_review: true,
  },
  {
    rule_id: 'kpold-237-diaxeirisi-dikastis',
    kpold_article: 'ΚΠολΔ 237 (Ν. 5221/2025 άρθρο 27)',
    title_gr: 'Διάταξη εισηγητή δικαστή — 30 ημέρες (από 1/1/2026)',
    description_gr: 'Μετά τη χρέωση, ο εισηγητής δικαστής μπορεί να εκδώσει εντός 30 ημερών Διάταξη για: αοριστία, μη επίδοση, αδυναμία προχωρήσεως. Κοινοποίηση ηλεκτρονικά στον δικηγόρο.',
    trigger_event: 'χρέωση_υπόθεσης_σε_εισηγητή',
    duration: { value: 30, unit: 'days' },
    deadline_kind: 'δικαστική_ευχέρεια',
    business_days_only: false,
    skip_august: true,
    weekend_rollover: 'next_business_day',
    notes_gr: 'ΔΕΝ είναι ανατρεπτική — η μη έκδοση δεν ακυρώνει τη διαδικασία.',
    edge_cases: [
      'Μη έκδοση Διάταξης: δεν ακυρώνει διαδικασία',
      'Ισχύει από 1/1/2026',
    ],
    frequency_score: 6,
    last_amended_by: 'Ν. 5221/2025 άρθρο 27',
    version: 'v2',
    effective_from: '2026-01-01',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 άρθρο 27 (νέο ΚΠολΔ 237)',
    requires_legal_review: false,
  },
  // -------------------------------------------------------------------------
  // kpold-130 — SHOWSTOPPER #2 (Themis v2 final review)
  // Νέος rule από Θέμιδα: εκκρεμείς ανακοπές με δικάσιμο > 16/9/2026
  // Warning-only: duration=null → engine επιστρέφει warning, όχι deadline
  // -------------------------------------------------------------------------
  {
    rule_id: 'kpold-130-epanaprosdiorismos-ekkremon',
    kpold_article: '130 (νέο)',
    title_gr: 'Επαναπροσδιορισμός εκκρεμών ανακοπών εκτέλεσης',
    description_gr: 'Εκκρεμείς ανακοπές 632/633§2/933/979/986 με δικάσιμο μετά 16/9/2026 αποσύρονται αυτοδικαίως εκτός αν υποβληθεί αίτηση επαναπροσδιορισμού επί ποινή απαραδέκτου μέσω ηλεκτρονικής πλατφόρμας (νέο ΚΠολΔ 131).',
    trigger_event: 'δικάσιμος_μετά_16_9_2026',
    duration: null,
    deadline_kind: 'ανατρεπτική',
    business_days_only: false,
    skip_august: false,
    weekend_rollover: 'next_business_day',
    notes_gr: 'WARNING-ONLY rule: δεν υπολογίζει deadline. Επιστρέφει μόνο critical warning για χειροκίνητο έλεγχο. Εξαιρούνται: 954§4 και 973§6.',
    edge_cases: [
      'Αν δικάσιμος ≤ 16/9/2026: rule δεν εφαρμόζεται',
      'Αν δικάσιμος > 16/9/2026 + αίτηση δεν υποβλήθηκε: ανακοπή απαράδεκτη',
      'Αίτηση επαναπροσδιορισμού = κλήση (ΚΠολΔ 130§2)',
    ],
    frequency_score: 9,
    last_amended_by: 'Ν. 5221/2025 άρθρο 105 + Ν. 5264/2025 άρθρα 130, 131, 142',
    version: 'v2',
    effective_from: '2026-09-16',
    effective_until: null,
    legal_source: 'Ν. 5221/2025 art. 105 + Ν. 5264/2025 άρθρο 130 παρ. 1-3 + άρθρο 142 (CODIFIED)',
    requires_legal_review: false,
    warnings_gr: [
      'ΚΡΙΣΙΜΟ: Έλεγξε ΚΑΘΕ εκκρεμή ανακοπή 632/933/633§2/979/986 με δικάσιμο μετά 16/9/2026 — κίνδυνος αυτόματης απόσυρσης επί ποινή απαραδέκτου (Ν. 5264/2025 άρθρο 142). Υποχρεωτική υποβολή αίτησης επαναπροσδιορισμού μέσω ηλεκτρονικής πλατφόρμας (νέο ΚΠολΔ 131).',
    ],
  },
];

export default STATIC_RULES;
